import { expect, type Locator, type Page } from '@playwright/test';
import type { RuntimeConfig } from '@config/runtimeConfig';
import { BasePage } from './basePage';
import { Logger } from '@utils/logger';

export class LoginPage extends BasePage {
  readonly signInUsingUsername: Locator;
  readonly usernameInput: Locator;
  readonly nextButton: Locator;
  readonly passwordInput: Locator;
  readonly profileMenuHeaderButton: Locator;
  readonly expandedProfileMenu: Locator;
  readonly accessDeniedMessage: Locator;
  readonly buttonTryAgain: Locator;
  readonly verifyAuthenticationMethodsLink: Locator;
  readonly txtCodesGeneratedKosmosApp: Locator;
  readonly txtEnterSixDigitCodeKosmosApp: Locator;
  readonly txtEmailCodeTo: Locator;
  readonly authenticationMethodOptions: Locator;
  readonly txtEnterVerificationCode: Locator;
  readonly passcodeInput: Locator;
  readonly txtProfileCommunityNameRole: Locator;
  readonly txtPushNotification: Locator;
  readonly txtApprovePushSignIn: Locator;
  readonly txtDoNotSetUpAuthMethod: Locator;
  readonly lblApproveSignIn: Locator;
  readonly lblPushSentToEnrolled: Locator;
  readonly imgQrCode: Locator;

  constructor(page: Page, config: RuntimeConfig) {
    super(page, config);
    this.signInUsingUsername = page.locator('[aria-label="Passwordless users, login here."]').filter({ hasText: "USERNAME" });
    this.usernameInput = page.locator('input#username');
    this.nextButton = page.getByRole('button', { name: "Next >" });
    this.passwordInput = page.locator('input#password');
    this.profileMenuHeaderButton = page.locator('header button');
    this.expandedProfileMenu = page.locator('#menu-list-grow');
    this.accessDeniedMessage = page.getByText('Your access has been denied');
    this.buttonTryAgain = page.getByText('Try Again?');
    this.verifyAuthenticationMethodsLink = page.locator('h1 + div p').filter({ hasText: 'Choose an authentication method' });
    this.txtCodesGeneratedKosmosApp = page.locator("//*[text()='Codes generated by 1Kosmos app']");
    this.txtEnterSixDigitCodeKosmosApp = page.locator("//*[text()='Enter 6-digit code generated by the 1Kosmos app']");
    this.txtEmailCodeTo = page.locator("//*[text()='Email code to']");
    this.authenticationMethodOptions = page.locator('//h1//following-sibling::div//p//following-sibling::div');
    this.txtEnterVerificationCode = page.getByLabel('Enter your verification code');
    this.passcodeInput = page.locator('#passcode');
    this.txtProfileCommunityNameRole = page.locator("(//li[@role='menuitem']//p)[2]");
    this.txtPushNotification = page.locator("//*[text()='Push Notification']");
    this.txtApprovePushSignIn = page.locator("//*[text()='Approve sign-ins via push notification sent to the 1Kosmos app']");
    this.txtDoNotSetUpAuthMethod = page.locator("//*[text()='Sorry, you do not have any authentication methods setup. Please contact your administrator.']");
    this.lblApproveSignIn = page.locator("//label[@for='passcode']").filter({ hasText: 'Approve your Sign In' });
    this.lblPushSentToEnrolled = page.locator("[for='passcode'] + div");
    this.imgQrCode = page.locator("a[href*='/sessions/session/']");
  }

  async openSignInUsingUsername() {
    Logger.log('UI', 'ACTION', 'Opening sign-in using username option on login page');
    await this.signInUsingUsername.waitFor({ state: 'visible' });
    await this.click(this.signInUsingUsername, 'Username Toggle');
    await this.expectToBeVisible(this.usernameInput, 'Username Field');
  }

  async submitUsername(username: string) {
    const isVisible = await this.isElementVisible(this.usernameInput, 'Username Field');
    if (!isVisible) {
      await this.openSignInUsingUsername();
    }
    await this.type(this.usernameInput, username, 'Username Input');
    await this.click(this.nextButton, 'Username Next Button');
    await this.page.waitForTimeout(3000);
  }

  async submitPassword(password: string) {
    const value: boolean = await this.isElementVisible(this.passwordInput, 'Password Innput field');
    this.expectToBeTrue(value, 'Password Input field');
    await this.type(this.passwordInput, password, 'Password Input');
    await this.click(this.nextButton, 'Password Next Button');
  }

  async verifyLoginSuccess(role: string) {
    await this.expectToHaveUrl(this.page, /dashboard/, 'Dashboard Page');
    await this.waitForSelector(this.profileMenuHeaderButton, 'Username Field');
    await this.click(this.profileMenuHeaderButton, 'Profile Menu Trigger');
    const expectedText = `${this.config.communityName} | ${role}`;
    const actualText: string = await this.getTextFromLocator(this.txtProfileCommunityNameRole, 'Get text for Community name and Role in Profile Menu');
    expect(actualText).toBe(expectedText);
    Logger.log('SUCCESS', `Authentication Journey verified for: ${role}`);
  }

  async logout(username: string) {
    const isMenuOpen = await this.isElementVisible(this.expandedProfileMenu, 'Expanded Profile Menu');
    if (!isMenuOpen) {
      Logger.log('UI', 'LOGOUT', `Profile menu is closed for ${username}. Expanding...`);
      await this.click(this.profileMenuHeaderButton, 'Profile Menu Trigger');
    }
    const logoutItem = this.page.getByRole('menuitem', { name: 'Logout', exact: true });
    await this.expectToBeVisible(logoutItem, 'Logout Menu Item');
    await this.click(logoutItem, 'Logout Menu Item');
    Logger.log('SUCCESS', `User logged out successfully for ${username}`);
  }

  async verifyAccessDenied() {
    await this.expectToBeVisible(this.accessDeniedMessage, 'Access Denied Message');
    await this.expectToBeVisible(this.buttonTryAgain, 'Try Again Button');
    Logger.log('UI', 'ACTION', 'Confirmed: User access restricted as per Rules Engine.');
  }

  async verifyAuthenticationMethodSelection() {
    await this.expectToBeVisible(this.verifyAuthenticationMethodsLink, 'Verify Authentication Methods selection');
    Logger.log('UI', 'ACTION', 'Confirmed: User prompted to select from multiple authentication methods as per Rules Engine.');
  }

  async verifyOnlyEmailOTPAuthenticationMethod() {
    const emailOtpOption = this.page.locator('label').filter({ hasText: 'Email OTP' });
    await this.expectToBeVisible(emailOtpOption, 'Email OTP Authentication Method Option');
    Logger.log('UI', 'ACTION', 'Confirmed: User presented with Email OTP as the only authentication method option as per Rules Engine.');
  }

  async verifyCodesGeneratedByKosmosAppIsVisible() {
    await this.expectToBeVisible(this.txtCodesGeneratedKosmosApp, 'Codes Generated by 1Kosmos App Text');
    Logger.log('UI', 'ACTION', 'Confirmed: Codes generated by 1Kosmos app are visible.');
    await this.expectToBeVisible(this.txtEnterSixDigitCodeKosmosApp, 'Enter the 6-digit code generated by 1Kosmos app Text');
    Logger.log('UI', 'ACTION', 'Confirmed: Prompt to enter the 6-digit code generated by 1Kosmos app is visible.');
  }

  async verifyEmailOTPAuthenticationMethodIsDisplayed() {
    await this.expectToBeVisible(this.txtEmailCodeTo, 'Email OTP Authentication Method Option');
    Logger.log('UI', 'ACTION', 'Confirmed: User presented with Email OTP as an authentication method option as per Rules Engine.');
  }

  async verifyOnlySelectedAuthenticationMethodsIsDisplayed(count: number) {
    await this.expectToHaveCount(this.authenticationMethodOptions, count, 'Unexpected number of authentication method options displayed');
    Logger.log('UI', 'ACTION', `Confirmed: Only the expected authentication method options are visible as per Rules Engine. Expected count: ${count}`);
  }

  async clickOnEmailOTPAuthenticationMethod() {
    await this.click(this.txtEmailCodeTo, 'Clicking on Email OTP Authentication Method Option');
    Logger.log('UI', 'ACTION', 'Clicked on Email OTP authentication method option.');
  }

  async enterVerificationCode(code: string) {
    await this.expectToBeVisible(this.txtEnterVerificationCode, 'Enter Verification Code label and input');
    await this.page.waitForTimeout(1000);
    await this.type(this.passcodeInput, code, 'Enter Verification Code Input');
    await this.page.waitForTimeout(2000);
    Logger.log('UI', 'ACTION', 'Entered verification code and submitted for authentication.');
  }

  async verifyPushNotificationAuthMethodIsDisplayed() {
    await this.expectToBeVisible(this.txtPushNotification, "Push Notification Text");
    await this.expectToBeVisible(this.txtApprovePushSignIn, "Approve Push Sign in Text");
    Logger.log('UI', 'ACTION', 'Confirmed: User presented with Push Notification as an authentication method option as per Rules Engine.');
  }

  async clickOnPushNotificationAuthenticationMethod() {
    await this.click(this.txtPushNotification, 'Clicking on PUSH Notification Authentication Method Option');
    Logger.log('UI', 'ACTION', 'Clicked on PUSH Notification authentication method option.');
  }

  async verifyDoNotSetUpAuthMethodsIsDisplayed() {
    await this.expectToBeVisible(this.txtDoNotSetUpAuthMethod, "Sorry, Do not have authentication methods");
    Logger.log('UI', 'ACTION', 'Confirmed: User displayed with Sorry, you do not have any authentication methods.');
  }

  async verifyPushNotificationSignInScreen() {
    await this.expectToBeVisible(this.lblApproveSignIn, "Approve sign in header");
    await this.expectElementToContainText(this.lblPushSentToEnrolled, "Accept the push notification to login.", "Push notification status label banner");
    Logger.log('UI', 'ACTION', 'Confirmed: User displayed with Push notification has been sent to registered device');
  }

  async verifyQRCodeSignInScreen() {
    await this.expectToBeVisible(this.imgQrCode, "QR Code Image");
    Logger.log('UI', 'ACTION', 'Confirmed: User displayed with QR Code');
  }

  async getQRSessionData(): Promise<{ sessionID: string; publicKey: string }> {
    const qrUrl = await this.getAttributeValue(this.imgQrCode, "href", "QR Code Image");
    Logger.log('UI', 'ACTION', `Extracted QR Target URL: ${qrUrl}`);

    let sessionID = '', publicKey = '';

    try {
      const response = await fetch(qrUrl);
      const data = await response.json();

      sessionID = data.sessionId || '';
      publicKey = data.publicKey || '';

      expect(sessionID).not.toBe('');
      expect(publicKey).not.toBe('');

      Logger.log('SUCCESS', `Extracted Session ID: ${sessionID}`);
      Logger.log('SUCCESS', `Extracted Public Key: ${publicKey.substring(0, 15)}...`);
    } catch (error: any) {
      Logger.log('ERROR', `Failed to fetch session data from URL. Error: ${error.message}`);
      throw error;
    }
    return { sessionID, publicKey };
  }

}